name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./webApp
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      working-directory: ${{env.working-directory}}
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f webApp/requirements.txt ]; then pip install -r webApp/requirements.txt; fi
    - name: Analysing the code with pylint
      working-directory: ${{env.working-directory}}
      run: |
        pylint $(git ls-files 'app_server.py')
        pylint $(git ls-files 'sample_test.py')
